#!/bin/bash

# List of directories to stow
DIRECTORIES="git tmux zsh"

for dir in $DIRECTORIES; do
    echo "Stowing $dir..."
    stow -v -R $dir # -v for verbose, -R for restow to handle updates
done

# Make sure the submodule is updated
echo "Updating submodules..."
git submodule update --init --recursive

# Stow .config directory separately
echo "Stowing .config directory..."
stow -v -R -t ~/.config .config

